### ISSUE TITLE
Still try to display some revisions, even if one of the revision URLs is invalid

### ISSUE THREAD

**Issue by edmorley** [peterbe/whatsdeployed#10]
1) Visit https://whatsdeployed.paas.allizom.org/?owner=mozilla&repo=treeherder&name[]=Stage&url[]=https://treeherder.allizom.org/revision.txt&name[]=Prod&url[]=https://treeherder.mozilla.org/some-file-that-doesnt-exist

Expected:
Revisions for 'stage' appear, with an error at the top of the page saying the revision file for prod was invalid.

Actual:
No revisions appear at all, just the error saying the revision file was invalid.

--

Use-case: We recently moved our revision file and during the transition the URL was broken - and everyone using the existing What's Deployed URL (particularly those who'd bookmarked the shortlink) got an unusable page, even though one of the revision URLs was still valid and would have provided useful information in the meantime.

**Comment by edmorley** [comment]
The response from `/shas` normally:
```json
{
  "deployments": [
    {
      "bugs": [],
      "name": "Stage",
      "sha": "90576b9fd9a0b7727072151c00042ea47c719161"
    },
    {
      "bugs": [],
      "name": "Prod",
      "sha": "cc78bb50eafa37f4d99ffd408a8ea23a0c95cbd7"
    }
  ]
}
```

For the error case:
```json
{
  "error": "Doesn't look like a sha\n (<html>\n <body>\n <h1>Page Not found</h1>\n </body>\n</html>) on https://treeherder.mozilla.org/some-file-that-doesnt-exist"
}
```

Whereas I think something like this would be more useful:
```json
{
  "deployments": [
    {
      "bugs": [],
      "name": "Stage",
      "sha": "90576b9fd9a0b7727072151c00042ea47c719161"
    },
    {
      "name": "Prod",
      "error": "Doesn't look like a sha\n (<html>\n <body>\n <h1>Page Not found</h1>\n </body>\n</html>) on https://treeherder.mozilla.org/some-file-that-doesnt-exist"
    }
  ]
}
```

**Comment by peterbe** [comment]
That feels unsafe to me. Suppose you only have 2 URLs that you're comparing. And if one of them fails you can't find a common sha which they have in common. And then you'd have to simply hope that there are at least 2 other branches that we can use.

**Comment by edmorley** [comment]
Ah I didn't realise the single URL case didn't work at present.

For single URL I think it should compare against master (or some other specified branch), since it can still compare between <SHA FROM URL> and <master>.

With that added, I guess this would then be viable?

**Comment by edmorley** [comment]
We now have three instances listed, so with one being missing, it would still be possible to display changes for the other two.
