### ISSUE TITLE
Support URLs that are JSON

### ISSUE THREAD

**Issue by peterbe** [peterbe/whatsdeployed#12]
Suppose you point whatsdeployed to a file [like this](https://testpilot.firefox.com/__version__) then to get the sha you need to parse the JSON and somehow pick out what key points to the sha.

**Comment by peterbe** [comment]
cc @edmoz @lmorchard

**Comment by peterbe** [comment]
@willkg I have, I think, upgraded whatsdeployed.io now. Care to try it?

**Comment by willkg** [comment]
It works super! Thank you! https://whatsdeployed.io/s-Up2
