### ISSUE TITLE
How do I use this service?

### ISSUE THREAD

**Issue by sindhus** [peterbe/whatsdeployed#16]
hi! thanks for making this

How do I use this service to check what's been deployed? I don't understand the fields "revision" and "Revision URLS". Say if I have http://github.com/blah_org/blah_repo and they deploy whatever they push to master, how do I use your service to check the commits deployed?

Thanks.

**Comment by peterbe** [comment]
Ah. Clearly the service isn't user friendly for first-timers. 

At some of my work projects we have a deployment bot that, as part of updating everything on the server, also writes the current git SHA to a file that is served straight from Nginx. E.g. https://air.mozilla.org/media/revision
That's the URL to go with the label "Prod". 

If you can think of better ways to explain this I'd love to put in a blurb on the home page.

**Comment by peterbe** [comment]
Solved with https://github.com/peterbe/whatsdeployed/commit/b766facd693c98a2fd403b4a5cf3a6f1dc6d61a3
