### ISSUE TITLE
Switch from BzAPI to the Bugzilla native REST API

### ISSUE THREAD

**Issue by edmorley** [peterbe/whatsdeployed#17]
Since the former is deprecated and 2-10x slower in many cases. See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1301541
https://bugzilla.mozilla.org/show_bug.cgi?id=1035804

https://github.com/peterbe/whatsdeployed/blob/130e6941b34c25baf8df2b1997f85526c65fafd7/static/main.js#L239-L246

**Comment by peterbe** [comment]
Thank you! I can't believe it's not been noticed sooner.

**Comment by edmorley** [comment]
You're welcome - thank you for updating :-)
