### ISSUE TITLE
HTTP 500 from /shas for treeherder.allizom.org (which uses SNI)

### ISSUE THREAD

**Issue by edmorley** [peterbe/whatsdeployed#18]
Visiting:
https://whatsdeployed.io/?owner=mozilla&repo=treeherder&name[]=Stage&url[]=https://treeherder.allizom.org/revision.txt&name[]=Prod&url[]=https://treeherder.mozilla.org/revision.txt

Results in:
"F' it! I give up! This is taking too long."
...and the call to `/shas` resulted in an HTTP 500.

The last time this worked was at least several weeks ago.

Specifically prod works:
https://whatsdeployed.io/?owner=mozilla&repo=treeherder&name[]=Prod&url[]=https://treeherder.mozilla.org/revision.txt

...but stage doesn't:
https://whatsdeployed.io/?owner=mozilla&repo=treeherder&name[]=Stage&url[]=https://treeherder.allizom.org/revision.txt

One difference between stage and prod, is that stage has recently been switched to Heroku's new SNI based SSL ([bug 1320303](https://bugzilla.mozilla.org/show_bug.cgi?id=1320303)), whereas prod hasn't yet (but will shortly).

If that is the case, then either:
1) the Python install needs to be upgraded to >=2.7.9.
2) or the requirements file needs to be updated to include `requests[security]`, so that [the packages](https://github.com/kennethreitz/requests/blob/580b45dd3caced54a1621ea0ffa88f20af9af4ea/setup.py#L98) that urllib3 requires for SNI support are installed (note `cryptography` requires the following packages: build-essential libssl-dev libffi-dev python-dev).

In addition, the error message could be improved to:
* say which request actually failed (eg include the URL, so it's clear which prod vs stage instance was problematic).
* correctly distinguish between failures to connect and timeouts, rather than calling everything a timeout (the UI doesn't pick up that the call to `/shas` resulted in an HTTP 500).

**Comment by peterbe** [comment]
Just yesterday I moved whatsdeployed to a new server where I only use Python 3. (3.5 to be exact).
Without reading too deeply into this (I'm on leave), I did click the first URL and that works now.

**Comment by peterbe** [comment]
Close?

**Comment by edmorley** [comment]
Ah great - working now thank you :-)
