### ISSUE TITLE
socorro whatsdeployed kicks up http 500

### ISSUE THREAD

**Issue by willkg** [peterbe/whatsdeployed#19]
This is the short link for Socorro whatsdeployed stuff:

https://whatsdeployed.io/s-7M7

At the moment, it's kicking up an HTTP 500 error. If I go to the "full url":

https://whatsdeployed.io/?repo=socorro&owner=mozilla&name[]=Prod&name[]=Stage&url[]=https%3A%2F%2Fcrash-stats.mozilla.com%2Fstatus%2Frevision%2F&url[]=https%3A%2F%2Fcrash-stats.allizom.org%2Fstatus%2Frevision%2F

That works fine.

@peterbe Any idea what's going on?

**Comment by peterbe** [comment]
Clearly, when I rewrote it in Python 3, I failed to test [this line](https://github.com/peterbe/whatsdeployed/blob/dbe6c1607d3817fce23c9770eb95706403e3ae02/app.py#L301).
The error is: `AttributeError: module 'urllib' has no attribute 'urlencode'`

**Comment by willkg** [comment]
You rock! Thank you so much!

**Comment by peterbe** [comment]
Works now. Yay!

**Comment by peterbe** [comment]
You might think I'm hawkishly keeping an eye on github notifications and work email. Oohh how not true! Just a complete coincidence.
