### ISSUE TITLE
Could whats deployed also show tags?

### ISSUE THREAD

**Issue by Natim** [peterbe/whatsdeployed#29]
- [ ] Show tags for commit
- [ ] In case the common commit is not a tag show the diff until the next tag

**Comment by peterbe** [comment]
Tecken only deploys tags, except for the Dev instance. A tag is a commit. 
[And that works](https://whatsdeployed.io/s-5HY).

Perhaps you mean to display tags as the rows instead of commits. So some way to collapse a bunch of commits into individual tags. Hmm... Not sure how to do that.

**Comment by mythmon** [comment]
[Normandy](https://whatsdeployed.io/s-IwE) also deploys tags. What I would appreciate is that when a tag is on a commit, that the name of that tag be shown next to the commit. That is, it will have all the same rows as it does now, but each row would be annotated with tags if one exists.

**Comment by peterbe** [comment]
@mythmon Whatsdeployed loops over all commits. One loop per env. When all loops find a commit sha it has in common, it stops. It extracts stuff like commit message (obviously) for each commit in the looping (main thing in the table). Is the tag in there? Perhaps we can download the tags separately to build up a map of `sha -> tag name` or something.

**Comment by mythmon** [comment]
I'm not too familiar with the Github API, but I imagine downloading the tags separately and making a `sha -> tag name` mapping would be fruitful.

**Comment by peterbe** [comment]
Note-to-self; You can list ALL tags by repo: https://developer.github.com/v3/repos/#list-tags
Every release has a `tag_name` https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository

So it'd be one step first just to get the commit `sha --> tag name`, then you could make another mapping of `tag name --> release url`.

**Comment by peterbe** [comment]
It works!
<img width="1616" alt="screen shot 2018-06-19 at 11 19 01 am" src="https://user-images.githubusercontent.com/26739/41606849-a09db52e-73b2-11e8-8484-f8eeb9623dc3.png">

Basically, it makes a dict of `sha -> tag name` and whenever it shows/lists a sha, it also shows a little badge with the tag name. It's a start.

**Comment by Natim** [comment]
Nice :dancer:
