### ISSUE TITLE
Normandy isn't showing the latest deployments/tags

### ISSUE THREAD

**Issue by mythmon** [peterbe/whatsdeployed#97]
The [Whatsdeployed page for Normandy](https://whatsdeployed.io/s/Ic1/mozilla/normandy) doesn't seem to be working quite right. It isn't showing the latest tag, and it says stage and prod aren't up to date with dev. The `__version__` endpoints on the Normandy are correct, and the tags are on Github. I'm not sure what's up.

**Comment by peterbe** [comment]
Is it not just because 8728fabd690932234c291705ec97d12aa90123de (stage and prod's latest sha) is so far behind from 36caa11fa78dbee077dd046f47d964f458c40d76 (dev's latest sha) that it can't show the full diff.

**Comment by peterbe** [comment]
Could this be the explanation?
<img width="1227" alt="Screen Shot 2019-09-24 at 3 34 07 PM" src="https://user-images.githubusercontent.com/26739/65544201-c6bfa600-dee0-11e9-889d-cfd620a39310.png">

**Comment by mythmon** [comment]
Ah, I don't think it is quite that. But you're on the right track. I got confused because [the Github diff view between dev and prod](https://github.com/mozilla/normandy/compare/36caa11fa78dbee077dd046f47d964f458c40d76...8728fabd690932234c291705ec97d12aa90123de) only lists 3 commits.

Looking more closely at this, I notice that v1.124.2 (what's deployed on Prod) isn't an ancestor of the commit on dev, which Whats Deployed assumes (and I also assumed when I filed this issue). So You can't ever find prod by starting at dev and walking backwards. That's because v1.124.1 and v1.124.2 forked off the main line in a way I didn't expect.

I think the problem here is that the deployment model that Jared's using for Normandy isn't compatible with Whats Deployed. I can't think of a way to make the two compatible. I'm going to close this, since it isn't the kind of problem I originally though. It would be nice to detect this situation and give a warning, but I'm not really sure how to do that.

Thanks for taking a look, sorry for the noise.

**Comment by peterbe** [comment]
Whatsdeployed assumes the commits are all on one straight line. It would, as you say, be nice to figure out "Your commits are not on a straight line, we'll never be able to find a common denominator." but I'm not sure how to do that.
